//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("myclinicModel", "FK__appointme__docto__5165187F", "doctor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CinicAutomation.doctor), "appointment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CinicAutomation.appointment), true)]
[assembly: EdmRelationshipAttribute("myclinicModel", "FK__appointme__patie__52593CB8", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CinicAutomation.patient), "appointment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CinicAutomation.appointment), true)]

#endregion

namespace CinicAutomation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class myclinicEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new myclinicEntities object using the connection string found in the 'myclinicEntities' section of the application configuration file.
        /// </summary>
        public myclinicEntities() : base("name=myclinicEntities", "myclinicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myclinicEntities object.
        /// </summary>
        public myclinicEntities(string connectionString) : base(connectionString, "myclinicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myclinicEntities object.
        /// </summary>
        public myclinicEntities(EntityConnection connection) : base(connection, "myclinicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<appointment> appointments
        {
            get
            {
                if ((_appointments == null))
                {
                    _appointments = base.CreateObjectSet<appointment>("appointments");
                }
                return _appointments;
            }
        }
        private ObjectSet<appointment> _appointments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<doctor> doctors
        {
            get
            {
                if ((_doctors == null))
                {
                    _doctors = base.CreateObjectSet<doctor>("doctors");
                }
                return _doctors;
            }
        }
        private ObjectSet<doctor> _doctors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<patient> patients
        {
            get
            {
                if ((_patients == null))
                {
                    _patients = base.CreateObjectSet<patient>("patients");
                }
                return _patients;
            }
        }
        private ObjectSet<patient> _patients;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the appointments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToappointments(appointment appointment)
        {
            base.AddObject("appointments", appointment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the doctors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodoctors(doctor doctor)
        {
            base.AddObject("doctors", doctor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the patients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopatients(patient patient)
        {
            base.AddObject("patients", patient);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myclinicModel", Name="appointment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class appointment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new appointment object.
        /// </summary>
        /// <param name="a_pk_id">Initial value of the A_pk_id property.</param>
        /// <param name="patient_fk_id">Initial value of the patient_fk_id property.</param>
        /// <param name="doctor_fk_id">Initial value of the doctor_fk_id property.</param>
        /// <param name="a_datetime">Initial value of the A_datetime property.</param>
        /// <param name="a_criticality">Initial value of the A_criticality property.</param>
        /// <param name="a_reason">Initial value of the A_reason property.</param>
        /// <param name="a_status">Initial value of the A_status property.</param>
        public static appointment Createappointment(global::System.Int32 a_pk_id, global::System.Int32 patient_fk_id, global::System.Int32 doctor_fk_id, global::System.DateTime a_datetime, global::System.String a_criticality, global::System.String a_reason, global::System.String a_status)
        {
            appointment appointment = new appointment();
            appointment.A_pk_id = a_pk_id;
            appointment.patient_fk_id = patient_fk_id;
            appointment.doctor_fk_id = doctor_fk_id;
            appointment.A_datetime = a_datetime;
            appointment.A_criticality = a_criticality;
            appointment.A_reason = a_reason;
            appointment.A_status = a_status;
            return appointment;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 A_pk_id
        {
            get
            {
                return _A_pk_id;
            }
            set
            {
                if (_A_pk_id != value)
                {
                    OnA_pk_idChanging(value);
                    ReportPropertyChanging("A_pk_id");
                    _A_pk_id = StructuralObject.SetValidValue(value, "A_pk_id");
                    ReportPropertyChanged("A_pk_id");
                    OnA_pk_idChanged();
                }
            }
        }
        private global::System.Int32 _A_pk_id;
        partial void OnA_pk_idChanging(global::System.Int32 value);
        partial void OnA_pk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 patient_fk_id
        {
            get
            {
                return _patient_fk_id;
            }
            set
            {
                Onpatient_fk_idChanging(value);
                ReportPropertyChanging("patient_fk_id");
                _patient_fk_id = StructuralObject.SetValidValue(value, "patient_fk_id");
                ReportPropertyChanged("patient_fk_id");
                Onpatient_fk_idChanged();
            }
        }
        private global::System.Int32 _patient_fk_id;
        partial void Onpatient_fk_idChanging(global::System.Int32 value);
        partial void Onpatient_fk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 doctor_fk_id
        {
            get
            {
                return _doctor_fk_id;
            }
            set
            {
                Ondoctor_fk_idChanging(value);
                ReportPropertyChanging("doctor_fk_id");
                _doctor_fk_id = StructuralObject.SetValidValue(value, "doctor_fk_id");
                ReportPropertyChanged("doctor_fk_id");
                Ondoctor_fk_idChanged();
            }
        }
        private global::System.Int32 _doctor_fk_id;
        partial void Ondoctor_fk_idChanging(global::System.Int32 value);
        partial void Ondoctor_fk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime A_datetime
        {
            get
            {
                return _A_datetime;
            }
            set
            {
                OnA_datetimeChanging(value);
                ReportPropertyChanging("A_datetime");
                _A_datetime = StructuralObject.SetValidValue(value, "A_datetime");
                ReportPropertyChanged("A_datetime");
                OnA_datetimeChanged();
            }
        }
        private global::System.DateTime _A_datetime;
        partial void OnA_datetimeChanging(global::System.DateTime value);
        partial void OnA_datetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String A_criticality
        {
            get
            {
                return _A_criticality;
            }
            set
            {
                OnA_criticalityChanging(value);
                ReportPropertyChanging("A_criticality");
                _A_criticality = StructuralObject.SetValidValue(value, false, "A_criticality");
                ReportPropertyChanged("A_criticality");
                OnA_criticalityChanged();
            }
        }
        private global::System.String _A_criticality;
        partial void OnA_criticalityChanging(global::System.String value);
        partial void OnA_criticalityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String A_reason
        {
            get
            {
                return _A_reason;
            }
            set
            {
                OnA_reasonChanging(value);
                ReportPropertyChanging("A_reason");
                _A_reason = StructuralObject.SetValidValue(value, false, "A_reason");
                ReportPropertyChanged("A_reason");
                OnA_reasonChanged();
            }
        }
        private global::System.String _A_reason;
        partial void OnA_reasonChanging(global::System.String value);
        partial void OnA_reasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String A_status
        {
            get
            {
                return _A_status;
            }
            set
            {
                OnA_statusChanging(value);
                ReportPropertyChanging("A_status");
                _A_status = StructuralObject.SetValidValue(value, false, "A_status");
                ReportPropertyChanged("A_status");
                OnA_statusChanged();
            }
        }
        private global::System.String _A_status;
        partial void OnA_statusChanging(global::System.String value);
        partial void OnA_statusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myclinicModel", "FK__appointme__docto__5165187F", "doctor")]
        public doctor doctor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("myclinicModel.FK__appointme__docto__5165187F", "doctor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("myclinicModel.FK__appointme__docto__5165187F", "doctor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<doctor> doctorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<doctor>("myclinicModel.FK__appointme__docto__5165187F", "doctor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<doctor>("myclinicModel.FK__appointme__docto__5165187F", "doctor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myclinicModel", "FK__appointme__patie__52593CB8", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("myclinicModel.FK__appointme__patie__52593CB8", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("myclinicModel.FK__appointme__patie__52593CB8", "patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("myclinicModel.FK__appointme__patie__52593CB8", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("myclinicModel.FK__appointme__patie__52593CB8", "patient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myclinicModel", Name="doctor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class doctor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new doctor object.
        /// </summary>
        /// <param name="d_pk_id">Initial value of the D_pk_id property.</param>
        /// <param name="d_name">Initial value of the D_name property.</param>
        /// <param name="d_gender">Initial value of the D_gender property.</param>
        /// <param name="d_ph">Initial value of the D_ph property.</param>
        /// <param name="d_specialization">Initial value of the D_specialization property.</param>
        /// <param name="d_address">Initial value of the D_address property.</param>
        public static doctor Createdoctor(global::System.Int32 d_pk_id, global::System.String d_name, global::System.String d_gender, global::System.Int32 d_ph, global::System.String d_specialization, global::System.String d_address)
        {
            doctor doctor = new doctor();
            doctor.D_pk_id = d_pk_id;
            doctor.D_name = d_name;
            doctor.D_gender = d_gender;
            doctor.D_ph = d_ph;
            doctor.D_specialization = d_specialization;
            doctor.D_address = d_address;
            return doctor;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 D_pk_id
        {
            get
            {
                return _D_pk_id;
            }
            set
            {
                if (_D_pk_id != value)
                {
                    OnD_pk_idChanging(value);
                    ReportPropertyChanging("D_pk_id");
                    _D_pk_id = StructuralObject.SetValidValue(value, "D_pk_id");
                    ReportPropertyChanged("D_pk_id");
                    OnD_pk_idChanged();
                }
            }
        }
        private global::System.Int32 _D_pk_id;
        partial void OnD_pk_idChanging(global::System.Int32 value);
        partial void OnD_pk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String D_name
        {
            get
            {
                return _D_name;
            }
            set
            {
                OnD_nameChanging(value);
                ReportPropertyChanging("D_name");
                _D_name = StructuralObject.SetValidValue(value, false, "D_name");
                ReportPropertyChanged("D_name");
                OnD_nameChanged();
            }
        }
        private global::System.String _D_name;
        partial void OnD_nameChanging(global::System.String value);
        partial void OnD_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String D_gender
        {
            get
            {
                return _D_gender;
            }
            set
            {
                OnD_genderChanging(value);
                ReportPropertyChanging("D_gender");
                _D_gender = StructuralObject.SetValidValue(value, false, "D_gender");
                ReportPropertyChanged("D_gender");
                OnD_genderChanged();
            }
        }
        private global::System.String _D_gender;
        partial void OnD_genderChanging(global::System.String value);
        partial void OnD_genderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 D_ph
        {
            get
            {
                return _D_ph;
            }
            set
            {
                OnD_phChanging(value);
                ReportPropertyChanging("D_ph");
                _D_ph = StructuralObject.SetValidValue(value, "D_ph");
                ReportPropertyChanged("D_ph");
                OnD_phChanged();
            }
        }
        private global::System.Int32 _D_ph;
        partial void OnD_phChanging(global::System.Int32 value);
        partial void OnD_phChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D_email
        {
            get
            {
                return _D_email;
            }
            set
            {
                OnD_emailChanging(value);
                ReportPropertyChanging("D_email");
                _D_email = StructuralObject.SetValidValue(value, true, "D_email");
                ReportPropertyChanged("D_email");
                OnD_emailChanged();
            }
        }
        private global::System.String _D_email;
        partial void OnD_emailChanging(global::System.String value);
        partial void OnD_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String D_specialization
        {
            get
            {
                return _D_specialization;
            }
            set
            {
                OnD_specializationChanging(value);
                ReportPropertyChanging("D_specialization");
                _D_specialization = StructuralObject.SetValidValue(value, false, "D_specialization");
                ReportPropertyChanged("D_specialization");
                OnD_specializationChanged();
            }
        }
        private global::System.String _D_specialization;
        partial void OnD_specializationChanging(global::System.String value);
        partial void OnD_specializationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String D_address
        {
            get
            {
                return _D_address;
            }
            set
            {
                OnD_addressChanging(value);
                ReportPropertyChanging("D_address");
                _D_address = StructuralObject.SetValidValue(value, false, "D_address");
                ReportPropertyChanged("D_address");
                OnD_addressChanged();
            }
        }
        private global::System.String _D_address;
        partial void OnD_addressChanging(global::System.String value);
        partial void OnD_addressChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myclinicModel", "FK__appointme__docto__5165187F", "appointment")]
        public EntityCollection<appointment> appointments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<appointment>("myclinicModel.FK__appointme__docto__5165187F", "appointment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<appointment>("myclinicModel.FK__appointme__docto__5165187F", "appointment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myclinicModel", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new patient object.
        /// </summary>
        /// <param name="p_pk_id">Initial value of the P_pk_id property.</param>
        /// <param name="p_name">Initial value of the P_name property.</param>
        /// <param name="p_dob">Initial value of the P_dob property.</param>
        /// <param name="p_gender">Initial value of the P_gender property.</param>
        /// <param name="p_ph">Initial value of the P_ph property.</param>
        public static patient Createpatient(global::System.Int32 p_pk_id, global::System.String p_name, global::System.DateTime p_dob, global::System.String p_gender, global::System.Int32 p_ph)
        {
            patient patient = new patient();
            patient.P_pk_id = p_pk_id;
            patient.P_name = p_name;
            patient.P_dob = p_dob;
            patient.P_gender = p_gender;
            patient.P_ph = p_ph;
            return patient;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 P_pk_id
        {
            get
            {
                return _P_pk_id;
            }
            set
            {
                if (_P_pk_id != value)
                {
                    OnP_pk_idChanging(value);
                    ReportPropertyChanging("P_pk_id");
                    _P_pk_id = StructuralObject.SetValidValue(value, "P_pk_id");
                    ReportPropertyChanged("P_pk_id");
                    OnP_pk_idChanged();
                }
            }
        }
        private global::System.Int32 _P_pk_id;
        partial void OnP_pk_idChanging(global::System.Int32 value);
        partial void OnP_pk_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String P_name
        {
            get
            {
                return _P_name;
            }
            set
            {
                OnP_nameChanging(value);
                ReportPropertyChanging("P_name");
                _P_name = StructuralObject.SetValidValue(value, false, "P_name");
                ReportPropertyChanged("P_name");
                OnP_nameChanged();
            }
        }
        private global::System.String _P_name;
        partial void OnP_nameChanging(global::System.String value);
        partial void OnP_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime P_dob
        {
            get
            {
                return _P_dob;
            }
            set
            {
                OnP_dobChanging(value);
                ReportPropertyChanging("P_dob");
                _P_dob = StructuralObject.SetValidValue(value, "P_dob");
                ReportPropertyChanged("P_dob");
                OnP_dobChanged();
            }
        }
        private global::System.DateTime _P_dob;
        partial void OnP_dobChanging(global::System.DateTime value);
        partial void OnP_dobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String P_gender
        {
            get
            {
                return _P_gender;
            }
            set
            {
                OnP_genderChanging(value);
                ReportPropertyChanging("P_gender");
                _P_gender = StructuralObject.SetValidValue(value, false, "P_gender");
                ReportPropertyChanged("P_gender");
                OnP_genderChanged();
            }
        }
        private global::System.String _P_gender;
        partial void OnP_genderChanging(global::System.String value);
        partial void OnP_genderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String P_email
        {
            get
            {
                return _P_email;
            }
            set
            {
                OnP_emailChanging(value);
                ReportPropertyChanging("P_email");
                _P_email = StructuralObject.SetValidValue(value, true, "P_email");
                ReportPropertyChanged("P_email");
                OnP_emailChanged();
            }
        }
        private global::System.String _P_email;
        partial void OnP_emailChanging(global::System.String value);
        partial void OnP_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 P_ph
        {
            get
            {
                return _P_ph;
            }
            set
            {
                OnP_phChanging(value);
                ReportPropertyChanging("P_ph");
                _P_ph = StructuralObject.SetValidValue(value, "P_ph");
                ReportPropertyChanged("P_ph");
                OnP_phChanged();
            }
        }
        private global::System.Int32 _P_ph;
        partial void OnP_phChanging(global::System.Int32 value);
        partial void OnP_phChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String P_history
        {
            get
            {
                return _P_history;
            }
            set
            {
                OnP_historyChanging(value);
                ReportPropertyChanging("P_history");
                _P_history = StructuralObject.SetValidValue(value, true, "P_history");
                ReportPropertyChanged("P_history");
                OnP_historyChanged();
            }
        }
        private global::System.String _P_history;
        partial void OnP_historyChanging(global::System.String value);
        partial void OnP_historyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String P_address
        {
            get
            {
                return _P_address;
            }
            set
            {
                OnP_addressChanging(value);
                ReportPropertyChanging("P_address");
                _P_address = StructuralObject.SetValidValue(value, true, "P_address");
                ReportPropertyChanged("P_address");
                OnP_addressChanged();
            }
        }
        private global::System.String _P_address;
        partial void OnP_addressChanging(global::System.String value);
        partial void OnP_addressChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("myclinicModel", "FK__appointme__patie__52593CB8", "appointment")]
        public EntityCollection<appointment> appointments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<appointment>("myclinicModel.FK__appointme__patie__52593CB8", "appointment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<appointment>("myclinicModel.FK__appointme__patie__52593CB8", "appointment", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
