//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinicAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int drugID { get; set; }
        public string drugName { get; set; }
        public Nullable<System.DateTime> drugExpiry { get; set; }
        public string drugDescription { get; set; }
        public string drugDosage { get; set; }
        public Nullable<decimal> drugPrice { get; set; }
    }
}
