//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAutimation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianPrescription
    {
        public int PhysicianPrescriptionID { get; set; }
        public int PhysicianPrescriptionScheduleID { get; set; }
        public Nullable<int> PhysicianPrescriptionDrugID { get; set; }
        public string PhysicianPrescriptionDescription { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
