//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAutimation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderID { get; set; }
        public string PurchaseOrderName { get; set; }
        public int PurchaseQuantity { get; set; }
        public string PurchaseCompany { get; set; }
        public int PurchaseDrugID { get; set; }
        public int PurchaseSupplierID { get; set; }
        public string PurchaseOrderStatus { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
