//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinicAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public int LoginId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> patientFk { get; set; }
        public Nullable<int> physicianFk { get; set; }
        public Nullable<int> chemistFk { get; set; }
        public Nullable<int> adminFk { get; set; }
        public Nullable<int> supplierFk { get; set; }
        public Nullable<int> roleFk { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Chemist Chemist { get; set; }
        public virtual patient patient { get; set; }
        public virtual physician physician { get; set; }
        public virtual role role { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
